### ISSUE TITLE
mikroservis yapısı

### ISSUE THREAD

**Issue by ofcerci4826** [DevArchitecture/DevArchitecture#103]
Merhaba,

Dokümandaki https://devarchitecture.netlify.app/tr/docs/projectlayers#business bölümünde, devarchitecture'ın istenildiğinde monolitik ya da mikroservis gibi kullanılabileceği belirtilmiş. Acaba mikroservis mimarisine uygun başarıyla uygulayabilen varmı  ? Varsa kısaca bahsedebilir misiniz?

**Comment by keremvaris** [comment]
Merhaba öncelikle şunu belirtmek isterim resmi olarak kullanılan proje referanslarına hakim değilim. bununla beraber mikroservis gibi kullanılmasından değil bir mikroservis projesine hizmet verebileceğinden bahsetmeye çalışmıştım dokümanda ilginiz için teşekkür ederim
