### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by serdargungor** [DevArchitecture/DevArchitecture#13]
WebAPI'de Register üstünde [AllowAnonymous] olduğundan, admin olarak login olmak fark etmeksizin SecuredOperation hata fırlatmakta. [AllowAnonymous] kaldırınca düzelmektedir.

**Comment by kurtbogan88** [comment]
Selamlar.
Register işlemi için ilgili CQRS metodundan [SecuredOperation ] kaldırabilirsiniz. Zaten Register içi SecuredOperation olmaması gerekiyor. İlk committe düzelteceğim. AllowAnonymous da geri koyabilirsiniz.
