### ISSUE TITLE
Success Response'lar neden düz string olarak dönüyor?

### ISSUE THREAD

**Issue by mzuvin** [DevArchitecture/DevArchitecture#16]
Merhaba, Bazi yerlerde success responselar da json dönerken, bazi yerlerde string olarak dönüyor.  Tam tersi hata olan yerlerde ise yine düz string olarak dönüş oluyor. web api de düz string dönmek yanlış değil mi ?

**Comment by keremvaris** [comment]
DevArchitecture doğası multilanguage yapısı için öyle bir yol izledik. iyi çalışmalar dilerim.
