### ISSUE TITLE
RedisCacheManager get metodunda invalidcastexception

### ISSUE THREAD

**Issue by opcinyasin** [DevArchitecture/DevArchitecture#17]
Merhaba, projeme redis eklemeye çalışıyorum. Öncellikle redis bağlantısını yaptım ve redise datayı yazdırabiliyorum ama eklenen datayı alırken casting hatası alıyorum. Sanırım metodumun geri dönüş tipiyle redis ten gelen datanın tipi uyuşmuyor yardım edebilir misiniz? 

![coremodule](https://user-images.githubusercontent.com/34135190/113473986-ada09980-9475-11eb-9a76-61beb9f7bc26.png)

![exception](https://user-images.githubusercontent.com/34135190/113473987-af6a5d00-9475-11eb-9adc-d4a48de3d220.png)

![cacheaspect](https://user-images.githubusercontent.com/34135190/113474025-e80a3680-9475-11eb-8198-88add364f976.png)

![redismanager](https://user-images.githubusercontent.com/34135190/113473989-b1342080-9475-11eb-9779-32fe4ded7d1f.png)

**Comment by Sanchklyc** [comment]
Aynı problemi yaşıyorum, Redis her şeyi string olarak kaydediyor. Dönüş tipi de string oluyor bu nedenle. Her seferinde Get<T> methodunu kullanmak da bağımlılık yaratıyor. Çözülürse çok iyi olur :)

**Comment by ofcerci4826** [comment]
Merhaba yasin
Aynı problemi bende yaşıyorum, bu konu ile ilgili bir çözüm bulabildin mi ?

**Comment by opcinyasin** [comment]
Henüz bulamadım...

**Comment by halukgozcu** [comment]
Merhaba @opcinyasin, 

Geri dönüş tipin IDataResult şeklinde bir interface. Dilersen interface'i kullandığın yere "ISerializable" interfacenden inherit etmeyi, olmaması durumunda DataResult classından GetAll() metodunun geri dönüş tipini sağlamayı deneyebilir misin ?

İyi çalışmalar.

**Comment by opcinyasin** [comment]
Merhaba **@halukgozcu**

Yanıtınız için teşekkürler denedim ama işe yaramadı tekrar aynı hatayı aldım

**Comment by mkavici** [comment]
Sorun Redisin object tipi istememesi gibi görünüyor; biraz dolambaçlı yoldan reflection ile şu şekilde bir çözüm buldum @opcinyasin 
```
using Newtonsoft.Json;


namespace Portal.Business.BusinessAspects.Autofac
{
    public class CacheAspect : MethodInterception
    {
        private int _duration;
        private string _key;
        private ICacheManager _cacheManager;


        public CacheAspectTest( int duration = 60, string key = "")
        {
            _duration = duration;
            _cacheManager = ServiceTool.ServiceProvider.GetService<ICacheManager>();
            _key = key;
      
        }

        public override void Intercept(IInvocation invocation)
        {

            var returnType = invocation.Method.ReturnParameter.ParameterType;
            if (string.IsNullOrEmpty(_key))
            {
                var methodName = string.Format($"{invocation.Method.ReflectedType.FullName}.{invocation.Method.Name}");

                 var arguments = invocation.Arguments.ToList();
                _key = $"{methodName}({string.Join(",", arguments.Select(x => x?.ToString() ?? "<Null>"))})";

            }
            if (_cacheManager.IsAdd(_key))
            {

                string a = _cacheManager.Get<string>(_key);
                MethodInfo method = typeof(JsonConvert).GetMethods().FirstOrDefault(method => method.Name == "DeserializeObject" & method.IsGenericMethod == true);

                MethodInfo generic = method.MakeGenericMethod(invocation.Method.ReturnParameter.ParameterType);
                invocation.ReturnValue = generic.Invoke(this, new object[] { a });
                                             
                return;
            }
            invocation.Proceed();
          
            _cacheManager.Add(_key, ToJson(invocation.ReturnValue), _duration);
        }

        private string ToJson(object obj)
        {

            JsonSerializerSettings jsonSerializerSettings = new JsonSerializerSettings
            {
                PreserveReferencesHandling = PreserveReferencesHandling.Objects,
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
                NullValueHandling = NullValueHandling.Ignore,
                StringEscapeHandling = StringEscapeHandling.EscapeHtml
            };
           return JsonConvert.SerializeObject(obj, Formatting.None, jsonSerializerSettings);//.Replace('"', '\'');
            

        }
    }
}

```

**Comment by byerlikaya** [comment]
Merhabalar,

Bu konu ile ilgili çözüm bulabilen oldu mu?
