### ISSUE TITLE
Could not load file or assembly 'Microsoft.EntityFrameworkCore.Design, Version=5.0.5.0, 

### ISSUE THREAD

**Issue by serdargungor** [DevArchitecture/DevArchitecture#21]
Merhaba, Sunucuda 5.0.5 hosting bundle yüklü olduğu halde aşağıdaki hata dönmektedir.
Publish ettiğimde Microsoft.EntityFrameworkCore.Design.dll dosyası oluşmuyor.

![IPD - 79 98 134 2 - Uzak Masaüstü Bağlantısı_2](https://user-images.githubusercontent.com/7539423/115411186-ee313e80-a1fb-11eb-89e3-2d9cc8d3c555.jpg)

**Comment by keremvaris** [comment]
Merhaba problemi çözdüğünüzü düşünüyorum. Ancak yine de bir proje yayınlama dokümanı ekledim. https://www.devarchitecture.net/docs/projeyayinlama adresinden ulaşabilirsiniz. mutlu kodlamalar dilerim.

**Comment by serdargungor** [comment]
Teşekkürler, Elinize sağlık.
