### ISSUE TITLE
CacheAspect

### ISSUE THREAD

**Issue by serdargungor** [DevArchitecture/DevArchitecture#23]
Merhaba,

CacheAspect'de Parametrenin Class olduğu durumlarda, Class'ın içindeki parametreler görülmüyor. aşağıdaki örnekte UserId değiştiğini algılamıyor hep ilk sorgulanan sonucu döndürmekte.

![DevArchitectureGetUserClaimLookupQuery cs at 574b6e74898e90f7f22beea8484dae62da695363 · DevArchitectureDevArchitecture - Google Ch](https://user-images.githubusercontent.com/7539423/115656554-13c66100-a33e-11eb-8d80-6135d9f987f5.jpg)

**Comment by keremvaris** [comment]
Merhaba problemin çözümünü aşağıdaki adresten inceleyebilirsiniz.  Desteğiniz için teşekkür ederim.
https://github.com/DevArchitecture/DevArchitecture/blob/master/Core/Aspects/Autofac/Caching/CacheAspect.cs
