### ISSUE TITLE
DevArchitectureFw Generate All Layers Hata

### ISSUE THREAD

**Issue by melihoguzozturk** [DevArchitecture/DevArchitecture#28]
Merhaba, DbFirst yaklaşımını tercih ettim ve ilgili tabloları veri tabanında oluşturdum ve ilişkilerini veri tabanından ayarladım. Daha sonra genaretor dan oluşturduğum tabloları seçerek oluştur butonuna tıkladım.
Entites>Concrete klasörünün içindeki entity sınıfında "DevArchitectureFw Generate All Layers" dediğim zaman hata alıyorum. 

![image](https://user-images.githubusercontent.com/1758437/122929631-d7ca6f00-d373-11eb-9574-56d75da195c6.png)

**Comment by keremvaris** [comment]
Merhaba entitiyler içinde bulunan ctor bloklarını silerek tekrar denerseniz problem olmayacaktır. İyi kodlama lar dilerim.
