### ISSUE TITLE
Unable to create an object of type 'MsDbContext'

### ISSUE THREAD

**Issue by ouzdev** [DevArchitecture/DevArchitecture#3]
Merhaba veritabanı olarak mssql kullanıyorum. 

WebAPI appsettings.Staging.json 

` "ConnectionStrings": {
    "DArchPgContext": "Host=localhost;Port=5432;Database=TestDb;Username=postgres;Password=test",
    "DArchMsContext": "server=DESKTOP-C5R88RR; database=OG.TestDb; integrated security=true;"
  },`

Bu şekilde db tanımlamasını yaptım. Package manager console penceresinde dokümantasyona göre ilerlediğimde hata alıyorum.

**Hata ;**

`PM> $env:ASPNETCORE_ENVIRONMENT='Staging'

PM> Add-Migration InitialCreate -context MsDbContext -OutputDir Migrations/Ms

Build started...

Build succeeded.

**Unable to create an object of type 'MsDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728**
PM> `

**Comment by keremvaris** [comment]
Merhaba Business projesi içerisinde bulunan Startup.cs içerisinde şu ifadeyi aratıp 
services.AddDbContext<ProjectDbContext>();  ConfigureStagingServices ve  ConfigureProductionServices metotları içinde services.AddDbContext<ProjectDbContext,MsDbContext>(); bu şekilde değiştirin lütfen. Ondan sonra migration çalıştırabilirsiniz. 
Dokümantasyon için https://www.devarchitecture.net/docs/veritabanisecimi buraya bakabilirsiniz. Mutlu geliştirmeler
