### ISSUE TITLE
Birden fazla veri tabanına bağlanma ve multi tenacy özelliği

### ISSUE THREAD

**Issue by melihoguzozturk** [DevArchitecture/DevArchitecture#37]
Birden fazla veri tabanına nasıl bağlanabiliriz ayrıca multi tenancy özelliği ekleyebilir miyiz? Bu konularda yardımcı olabilir misiniz?

**Comment by keremvaris** [comment]
Merhaba, bu sürüm için Multi Tenancy yeteneği geliştirmeyi düşünmüyorum.
