### ISSUE TITLE
transient connection failures

### ISSUE THREAD

**Issue by darkMelo** [DevArchitecture/DevArchitecture#39]
System.AggregateException: 'One or more errors occurred. (An exception has been raised that is likely due to a transient failure.)'

namespace Core.Utilities.Interceptors
{
    public abstract class MethodInterception : MethodInterceptionBaseAttribute
    {
        public override void Intercept(IInvocation invocation)
        {
            var isSuccess = true;
            OnBefore(invocation);
            try
            {
                invocation.Proceed();
                var result = invocation.ReturnValue as Task;
                result?.Wait();
            }
            catch (Exception e)
            {
                isSuccess = false;
                OnException(invocation, e);
                throw; // <-- issue AggregateException: transient connection failures
            }

**Comment by VeliGorgulu** [comment]
I know it's been a long time since the issue was opened. Maybe this can help, [see](https://www.thecodebuzz.com/enabling-transient-error-resiliency-enableretryonfailure/)
