### ISSUE TITLE
Arayuz kurulum problemi

### ISSUE THREAD

**Issue by muharrems** [DevArchitecture/DevArchitecture#4]
Merhaba,
WebAPI,  IIS_Staging de çalışır vaziyette iken UIPreparation üzerinde sağ tıklayıp Debug ve Start New Instance yaptığımda sonuç alamıyorum. Arayüz kurulmuyor. Terminal ekranında aşağıdaki satırlar geliyor. Ne yapmam gerekir. 
"""
WSAStartup: (10107) Bir sistem þagrisi basarisiz oldu.
WSAStartup: (10107) Bir sistem þagrisi basarisiz oldu.
WSAStartup: (10107) Bir sistem þagrisi basarisiz oldu.
WSAStartup: (10107) Bir sistem þagrisi basarisiz oldu.
WSAStartup: (10107) Bir sistem þagrisi basarisiz oldu.
WSAStartup: (10107) Bir sistem þagrisi basarisiz oldu.
Sistem belirtilen yolu bulamıyor.
WSAStartup: (10107) Bir sistem þagrisi basarisiz oldu.
WSAStartup: (10107) Bir sistem þagrisi basarisiz oldu.
"""

**Comment by keremvaris** [comment]
Merhaba;
Eğer kurulumlarınızın tam, güncelleştirmelerinizin tam olduğunu düşünüyorsanız, aşağıdaki komutu  yönetici olarak komut satırında çalıştırmayı deneyin. Eğer olmaz ise temiz kurulum yapmayı deneyin. 

`netsh winsock reset`
