### ISSUE TITLE
Detaylı Kullanım

### ISSUE THREAD

**Issue by fatihdurmaz** [DevArchitecture/DevArchitecture#48]
Merhabalar,

Bu mimari yapıyı örnek bir kullanım videosuyla anlatabilir misiniz? Örneğin entity oluşturduktan sonra birbirleriyle olan ilişkileri, mappin işlemi, ilişkili entity'lerin angular componetlerinde kullanımı.
Dökümantasyon yetersiz kalıyor bazı konularda. Daha detaylandırılsa süper olur.
Böyle güzel bir yapıyı bize sunduğunuz için teşekkür ederim.

**Comment by cemalkarabulakli** [comment]
Merhaba, 
Aşağıdaki linkteki videoları izlerseniz yapının tamamı olmasa da projede kullanılan bazı konseptleri ve ilişkileri daha iyi anlayabilirsiniz. 
https://youtube.com/playlist?list=PLqG356ExoxZVN7rC0KmMo0lvECK97VRZg


> Merhabalar,
> 
> Bu mimari yapıyı örnek bir kullanım videosuyla anlatabilir misiniz? Örneğin entity oluşturduktan sonra birbirleriyle olan ilişkileri, mappin işlemi, ilişkili entity'lerin angular componetlerinde kullanımı. Dökümantasyon yetersiz kalıyor bazı konularda. Daha detaylandırılsa süper olur. Böyle güzel bir yapıyı bize sunduğunuz için teşekkür ederim.
