### ISSUE TITLE
Proje İlk Kurulum Hakkında

### ISSUE THREAD

**Issue by fikretcaglar** [DevArchitecture/DevArchitecture#5]
Merhaba,
Dökümantasyon belirtilen işlemleri yapıp Mssql db context'e göre Business/Startup staging kısmında msdb context'e göre tanımlarımı güncelledim. 

Postgresql contexini kullanmak istemediğim için tanımlarımı sadece ms sql'e göre yaptım. Ancak şunu farkettim migrationı çalıştırdığımda dökümanda belirtilen örnek kullanıcılar mssql de oluşmamaktadır. language ve translate için örnek datalar oluşmaktadır. ama örnek kullanıcı ve role gibi kısımlar oluşmamakta. 

Bu bir eksiklik olabilir. belirtmek istedim.  ve böyle bir çalışma için Solid Team'e teşekkür ederim 

@engindemirog Hocam , istanbul'a geldiğinizde Haliç Üniversitesi'nde tekrar bir çayımızı içmeye bekliyoruz. (Solid Team deki diğer ekip arkadaşlarıda bekleriz.) :)

**Comment by mstfony** [comment]
Merhabalar, bende postgre de ilk migrationu yaparken şöyle bir hata aldım. Dbcontextte cümleciği elle girmeme rağmen aynı hatayı aldım. 
"Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Migrations.IMigrator'. This is often because no database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext"

**Comment by keremvaris** [comment]
> Merhaba,
> Dökümantasyon belirtilen işlemleri yapıp Mssql db context'e göre Business/Startup staging kısmında msdb context'e göre tanımlarımı güncelledim.
> 
> Postgresql contexini kullanmak istemediğim için tanımlarımı sadece ms sql'e göre yaptım. Ancak şunu farkettim migrationı çalıştırdığımda dökümanda belirtilen örnek kullanıcılar mssql de oluşmamaktadır. language ve translate için örnek datalar oluşmaktadır. ama örnek kullanıcı ve role gibi kısımlar oluşmamakta.
> 
> Bu bir eksiklik olabilir. belirtmek istedim. ve böyle bir çalışma için Solid Team'e teşekkür ederim
> 
> @engindemirog Hocam , istanbul'a geldiğinizde Haliç Üniversitesi'nde tekrar bir çayımızı içmeye bekliyoruz. (Solid Team deki diğer ekip arkadaşlarıda bekleriz.) :)

Merhaba ilginiz için teşekkürler. 
Herhangi bir problem yok. Migration dışında bir mekanizma işletiyoruz orada. DevArchitecture ilk ayağa kalktığı zaman yetkili kullanıcı ve yetkileri için otomatik olarak tüm kod içeriğini tarar ve [SecuredOperation] attribute gördüğü tüm metotlar için otomatik yetki tanımlamasını yapar. Bunun avantajı sistemde daha sonra ekleyeceğiniz komut ve/veya sorgular için yetkilendirme mekanizmasında ayrıca bir efor sarf etmeminizi sağlamak amaçlıdır.
İyi çalışmalar.

**Comment by keremvaris** [comment]
> Merhabalar, bende postgre de ilk migrationu yaparken şöyle bir hata aldım. Dbcontextte cümleciği elle girmeme rağmen aynı hatayı aldım.
> "Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Migrations.IMigrator'. This is often because no database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions object in its constructor and passes it to the base constructor for DbContext"

Merhaba;
Muhtemelen bir adımı atlıyorsunuz. Dokümanın ilgili kısmını referans olarak paylaşıyorum.  https://www.devarchitecture.net/docs/migration#postgresql

Herhangi bir problem yaşamanız dahilinde linkedin üzerinden iletişim kurabilirsiniz. 
iyi çalışmalar dilerim

**Comment by mstfony** [comment]
Teşekkürler , dediğiniz gibi bir kısmını atladım muhtemelen. Oldu .
