### ISSUE TITLE
Visual Studio 2022 Desteği

### ISSUE THREAD

**Issue by mstfony** [DevArchitecture/DevArchitecture#50]
Selamlar,
Marketplace de yer alan eklentiler Visual studio 2022 için güncellenecek mi ?

**Comment by fatihdurmaz** [comment]
Hocam herhangi bir geliştirme va yapılacağını düşünmüyorum, açılan issue lere cevap bile verilmiyor zaten.

**Comment by keremvaris** [comment]
> Selamlar, Marketplace de yer alan eklentiler Visual studio 2022 için güncellenecek mi ?

İyileştirme çalışmalarımız kapsamında 2022 ilk çeyreğine kadar Visual Studio 2022 için Marketplace güncellemesi yapmayı düşünmüyoruz.. Net 6 bağlı bileşen paketlerinin kararlı sürümlerini gözlemlemeye devam edeceğiz bir süre.
