### ISSUE TITLE
Visual Studio Extension hakkında.

### ISSUE THREAD

**Issue by mzuvin** [DevArchitecture/DevArchitecture#53]
Merhaba, Eklentileri açık kaynak yapmayı düşünüyor musunuz ? Kod oluşturucularını özelleştirmek için faydalı olurdu.

**Comment by keremvaris** [comment]
Öneriniz için teşekkürler. Kod Üreteci algoritmalarımızı açık kaynak olarak paylaşmayı düşünmüyorum.
