### ISSUE TITLE
DevArchitecture Menu not appearing

### ISSUE THREAD

**Issue by omeriqbal2019** [DevArchitecture/DevArchitecture#54]
Devarchitecture Menu is not appearing as shown in image.it is visible in some vs2019 installed on other machine and some of it not.Kindly suggest the fix for this
![image](https://user-images.githubusercontent.com/48888340/149383731-72979879-b4af-46b7-bd85-cc20d6da5097.png)

**Comment by fatihdurmaz** [comment]
if you don't see the menu, you have to right click on any entity.

**Comment by omeriqbal2019** [comment]
I did it. i told you some of vs2019 installed on other machine  it is not shown

**Comment by fatihdurmaz** [comment]
did you install the plugin?

https://marketplace.visualstudio.com/items?itemName=DevArchitectureTeams.DevArchitectureCodeGen

**Comment by omeriqbal2019** [comment]
Yes i tried still no menu appear

**Comment by keremvaris** [comment]
Hi! please make a clean install. There does not appear to be a problem
