### ISSUE TITLE
InTransaction Kullanımı Hk.

### ISSUE THREAD

**Issue by gokmensercan** [DevArchitecture/DevArchitecture#55]
Selamlar,

InTransaction methodunun kullanımını proje içerisinde göremedim. Bir handler içerisinde birden çok saveChanges() methodum bulunmakta, olası bir hataya karşılık RollBack yapabilmek için InTransaction methodunun kullanımını paylaşırsanız sevinirim.

**Comment by keremvaris** [comment]
Selamlar, eskiden transactional operasyonları henüz desteklemiyorken o metodu kullanıyordum. Eski projelerde kullanan varsa diye silmiyorum. Yerine bu aspecti kullanırsanız (TransactionScopeAspectAsync) problem yaşamayacağınızı düşünüyorum.
