### ISSUE TITLE
the install of devarchitecturegen was not successful for all the selected products.

### ISSUE THREAD

**Issue by omeriqbal2019** [DevArchitecture/DevArchitecture#58]
The install of devarchitecturegen was not successful for all the selected products.Please see the attached screen shot.
![1](https://user-images.githubusercontent.com/48888340/157887318-502aeaa5-d5ef-4032-ad80-4ec46c3fe370.png)

**Comment by keremvaris** [comment]
Hello, Please update Visual Studio 2022 to latest version
