### ISSUE TITLE
Deploy to Azure Devarchitecture webapi

### ISSUE THREAD

**Issue by omeriqbal2019** [DevArchitecture/DevArchitecture#59]
Is there any link tutorial how to deploy at azure dev architecture webpi .I tried to publish through visual studio and provide the credentials but i get Invalid exception swagger is not starting .Please if you can provide me tutorial link for dev architecture webapi upload Thanks.

**Comment by keremvaris** [comment]
Hello, there is a link below. Special tnx @VeliGorgulu
  https://devarchitecture.netlify.app/docs/projeyayinlamaazure
