### ISSUE TITLE
IResult

### ISSUE THREAD

**Issue by cemalkarabulakli** [DevArchitecture/DevArchitecture#71]
Hello, do you planning any upgrades to .NET 6, because when I set WEP API to .NET 6 returns the error: 

` "'IResult' is an ambiguous reference between 'Core.Utilities.Results.IResult' and 'Microsoft.AspNetCore.Http.IResult' WebAPI"?
	 `
We tried to use the .NET Core reference but they returned Task instead of bool and string.

**Comment by VeliGorgulu** [comment]
You can use this piece of code to fix this problem.
`using IResult = Core.Utilities.Results.IResult;`
OR
You can pull the branch that has already been updated to .Net 6.
[https://github.com/DevArchitecture/DevArchitecture/tree/master-Net6](url)
