### ISSUE TITLE
.Net 6 Desteği

### ISSUE THREAD

**Issue by fatihdurmaz** [DevArchitecture/DevArchitecture#78]
Merhaba, altyapıyi .net 6 için güncellemeyi düşünüyor musunuz.

**Comment by VeliGorgulu** [comment]
Sorunuzun cevabını bilmiyorum ancak .net 6 üzerinden ilerleyen aktif bir branch mevcut. 
Belki ilginizi çekebilir. [master-net6](https://github.com/DevArchitecture/DevArchitecture/tree/master-Net6)
