### ISSUE TITLE
RefreshToken

### ISSUE THREAD

**Issue by bircpartner** [DevArchitecture/DevArchitecture#8]
Merhaba,
Öncelikle böyle bir altyapı kurduğunuz için teşekkür ederim.  Bu yapının içine Refresh Token Implementasyonunu nasıl yapabiliriz?
İyi Günler.

**Comment by keremvaris** [comment]
Merhaba;
https://github.com/DevArchitecture/DevArchitecture/pull/30 geliştirmesiyle RefreshToken mekanizması eklenmiştir. 
en kısa zamanda marketplace ortamından da ulaşılabilir hale gelecektir.
iyi kodlamalar dilerim.

tnx @NihatCelik
