### ISSUE TITLE
MediatR NotificationHandler is getting called twice

### ISSUE THREAD

**Issue by mkozen** [DevArchitecture/DevArchitecture#82]
I've noticed that when i publish one notification the NotificationHandler is getting called twice. 

There are two registration of MediatR in the project.

Registration in the business startup:
`            services.AddMediatR(typeof(BusinessStartup).GetTypeInfo().Assembly);
`

Registration in the core module:
`            services.AddMediatR(Assembly.GetExecutingAssembly());
`

When i remove the registiration from the bussiness startup everything is fine. Also, i did not encounter any other effect of removing the registiration from bussiness startup. 

What is the purpose of registering Mediatr twice? How can I fix this problem if removing the registration from business startup is bad?

**Comment by VeliGorgulu** [comment]
It looks like a small overlooked situation. MediatR was recently removed from the Startup.cs by @keremvaris (master-Net6 branch). [See the commit](https://github.com/DevArchitecture/DevArchitecture/commit/cd684848e39a4a7c9f5ceb11eb55e13d31802a9e)
