### ISSUE TITLE
VS Extension Güncellemesi

### ISSUE THREAD

**Issue by fatihdurmaz** [DevArchitecture/DevArchitecture#89]
Merhaba, github master branche'da template .net 6 ya yükseltilmiş durumda. DevArchitecture Visual Studio Extensions paketi ise hala eski sürümde. Güncelleme ile ilgili bir çalışma olacak mı?

**Comment by turkiasoft** [comment]
Merhabalar .NET 7 ye yükseltme yapabilir misiniz. Extension lar eski kalmış DB  first kısmı VS2022 de çalışması postgresql ve sqlserver ikisinde de denedim. Şimdiden teşekkürler
@keremvaris @Huseyinb @serdargungor @kurtbogan88
