### ISSUE TITLE
Quotes.cs isimli class için Generate All Layer hatalı çalışıyor

### ISSUE THREAD

**Issue by atomdeniz** [DevArchitecture/DevArchitecture#9]
Concrete klasörüne eklediğim class'ta Generate All Layers komutunu çalıştırdığımda  Get***Query.cs kısmına geldiğinde eklenmiş olarak görüyor ve yapılan işlemi durduruyor. Repository gibi alanları eklemeden işlemi kapatıyor.

*Tools : DevArchitecture WebAPI Şablon ve DevArchitecture Code Generator

**Comment by kurtbogan88** [comment]
Merhaba. Daha önce aynı entity için "Generate All Layer" komutunu çalıştırmıydınız?

**Comment by atomdeniz** [comment]
Tekrar test ettiğimde ilk denemem olan Quotes.cs için hata aldığımı farkettim. Farklı class isimleri ile denediğimde hata almadım.

**Comment by kurtbogan88** [comment]
@atomdeniz selamlar. Entity için bir kez code generator " generate all layer" dedikten sonra aynı entityde  ikinci kez çalıştırmak için önceden oluşturulan class dosyalarını silmeniz gerekmektedir

**Comment by atomdeniz** [comment]
> @atomdeniz selamlar. Entity için bir kez code generator " generate all layer" dedikten sonra aynı entityde ikinci kez çalıştırmak için önceden oluşturulan class dosyalarını silmeniz gerekmektedir

Sıfır oluşturduğum projede de aynı hatayı alıyorum. İsimle alakalı özel bir durum zannediyorum.

**Comment by keremvaris** [comment]
Merhaba;
Entity ismini Quote yani tekil olarak kullanın. DevArchitecture yaşam döngüsü içerisinde CodeGenerator tekil isim kullanmanızı bekler. Özel durumu olan İngilizce kelimeleri takip edebilme yetkinliğine sahiptir.
