### ISSUE TITLE
Database First TrustServerCertificate Error

### ISSUE THREAD

**Issue by abdullahkahriman** [DevArchitecture/DevArchitecture#92]
Add **TrustServerCertificate** as checkbox on "DevArchitectureFw DbFirst Generator" screen.
**Because this option is not available, I get the error "Connected successfully to the server, but an error occurred during the login process"**

**Comment by serdargungor** [comment]
Add "Trust Server Certificate=True" to DArchMsContext.

**Comment by abdullahkahriman** [comment]
Already attached. However, I'm still getting an error. I noticed the error by taking a video because the console is closing

**Comment by osd1syc** [comment]
To solve above issue, in the DbfirstEntityGenerator dialog, in the server name put ; next to your server name and add TrustServerCertificate = true
No need to add ; or , or ' ' or " " to TrustServerSecurity =true line. Then you will be able to run databasefirst code generator successfully.
