### ISSUE TITLE
`TransactionScopeAspectAsync` Method Potential Bug

### ISSUE THREAD

**Issue by onurkanbakirci** [DevArchitecture/DevArchitecture#94]
https://github.com/DevArchitecture/DevArchitecture/blob/a3936a3bd1fd921d9ce84f09b41df4675fecb738/Core/Aspects/Autofac/Transaction/TransactionScopeAspectAsync.cs#L16-L29

In this section of `TransactionScopeAspectAsync` method, why `finally` block is being used? I think that `catch` block should be used instead `finally` to rollback in any error case. Otherwise, all transactions will be rolled back even if it is successfull.

**Comment by keremvaris** [comment]
Throwing an error would not be the right approach; instead, it would be more logical to roll back all operations. thank you for your interest
