### ISSUE TITLE
MemoryCacheManager Hatası

### ISSUE THREAD

**Issue by RecepElitok** [DevArchitecture/DevArchitecture#98]
merhaba
ilk olarak tüm getall isteklerine karşılık MSSQL den data geliyor,
2. kez getall isteklerine cache den geldiği için  bu hata ile karşılaşıyorum
yardımcı olabilir misiniz?

![Ekran görüntüsü 2023-08-03 213116](https://github.com/DevArchitecture/DevArchitecture/assets/141360301/db5daee1-d2bc-48f1-aa03-93c1071e5104)

**Comment by RecepElitok** [comment]
projeyi silip yeniden yükledim düzelti nuget paketlerinin farklı versiyon olmasından kaynaklanıyormuş

**Comment by keremvaris** [comment]
geri bilgilendirmeniz için teşekkür ederim
